import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import './globals.css'
import Sidebar from '../../components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Architecture Firm',
  description: 'Generated by JoshDev',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='overflow-x-hidden'>
          <Navbar />
          <Sidebar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
